---
openapi: 3.0.0
info:
  title: Synesthesia Reading App API
  description: The Synesthesia Reading App API allows access to users' documents and color profiles across devices.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/AFTOWNS99/Synesthesia-Reading-App/1.0.0
security:
- application:
  - read
  - write
tags:
  - name: documents
    description: Everything about your Documents
  - name: color profile
    description: Information about a user color profile
  - name: user
    description: Operations about user
paths:
  /documents/:
    get:
      tags: 
        - documents
      summary: Returns an array of documents
      operationId: document_get_list
      responses:
        "200":
          description: a JSON array of document objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
    post:
      tags: 
        - documents
      summary: Adds a document to a user's library
      operationId: document_add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        "201":
          description: Created
  /documents/{id}/:
    delete:
      tags:
        - documents
      summary: deletes the document with the given id from account storage
      operationId: document_destroy
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: No content
  /color_profile/:
    get:
      tags: 
        - color profile
      summary: Returns the entire color profile of a user
      responses:
        "200":
          description: a JSON dictionary of color-word pairs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Color_Profile'
    post:
      tags: 
        - color profile
      summary: add a key-value pair of grapheme/word and color to a Color Profile
      operationId: color_profile_add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Color_Pair'
        required: true
      responses:
        "201":
          description: Created
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
          example: id123
        title:
          type: string
          example: The Silmarillion
        text:
          type: string
        notes:
          type: array
          items:
            $ref: '#/components/schemas/Note'
    Note:
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        text:
          type: string
    Color_Profile:
      type: array
      items:
        $ref: '#/components/schemas/Color_Pair'
    Color_Pair:
      type: object
      properties:
        grapheme:
          type: string
          example: cat
        color:
          $ref: '#/components/schemas/Color'
    Color:
      type: object
      properties:
        R:
          type: integer
          example: 255
        G:
          type: integer
          example: 0
        B:
          type: integer
          example: 50
      description: RGB color
